[package]
name = "ascii-vid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"image" = "0.24.5"
"term_size" = "*"
"clearscreen" = "2.0.0"
